language: python
sudo: false
python:
 - "3.5"
env:
 - DJANGO_VERSION=1.9
 - DJANGO_VERSION=1.10   
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99" flake8
script:
 - ./run.sh test
 - ./run.sh check
